language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=3.1.*@dev
    - php: 7.0
      env: SYMFONY_VERSION=3.1.*@dev
    - php: 7.1
      env: SYMFONY_VERSION=3.1.*@dev

before_install:
  - composer validate
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update

install: composer update --prefer-source

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script: php vendor/bin/coveralls -v

notifications:
  email:
    - hello@lennerd.com

