language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=2.7.*

matrix:
  allow_failures:
    - php: 7
  include:
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*@dev
    - php: 7
      env: SYMFONY_VERSION=3.0.*@dev

before_script:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update

install: composer update --prefer-source

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script: php vendor/bin/coveralls -v

notifications:
  email:
    - hello@lennerd.com